db:
  image: postgres
  volumes:
    - ./create_hstore_extension.sh:/docker-entrypoint-initdb.d/create_hstore_extension.sh:ro

data:
  image: cogniteev/echo
  volumes:
    - /var/www/assets

uwsgi:
  restart: always
  image: vanessa/expfactory
  volumes_from:
    - data
  volumes:
    - .:/code
    - /var/www/static
  links:
    - db
    - redis

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
    - data
  links:
    - uwsgi

redis:
  restart: always
  image: redis
